// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vtn.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request_Type int32

const (
	Request_PING_MESSAGE Request_Type = 0
	Request_ACK_MESSAGE  Request_Type = 1
)

var Request_Type_name = map[int32]string{
	0: "PING_MESSAGE",
	1: "ACK_MESSAGE",
}

var Request_Type_value = map[string]int32{
	"PING_MESSAGE": 0,
	"ACK_MESSAGE":  1,
}

func (x Request_Type) String() string {
	return proto.EnumName(Request_Type_name, int32(x))
}

func (Request_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fdc682062a128624, []int{0, 0}
}

type Request struct {
	Type                 Request_Type `protobuf:"varint,1,opt,name=type,proto3,enum=main.Request_Type" json:"type,omitempty"`
	PingMessage          *PingMessage `protobuf:"bytes,2,opt,name=pingMessage,proto3" json:"pingMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdc682062a128624, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() Request_Type {
	if m != nil {
		return m.Type
	}
	return Request_PING_MESSAGE
}

func (m *Request) GetPingMessage() *PingMessage {
	if m != nil {
		return m.PingMessage
	}
	return nil
}

type PingMessage struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdc682062a128624, []int{1}
}

func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (m *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(m, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type AckMessage struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckMessage) Reset()         { *m = AckMessage{} }
func (m *AckMessage) String() string { return proto.CompactTextString(m) }
func (*AckMessage) ProtoMessage()    {}
func (*AckMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdc682062a128624, []int{2}
}

func (m *AckMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMessage.Unmarshal(m, b)
}
func (m *AckMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMessage.Marshal(b, m, deterministic)
}
func (m *AckMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMessage.Merge(m, src)
}
func (m *AckMessage) XXX_Size() int {
	return xxx_messageInfo_AckMessage.Size(m)
}
func (m *AckMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AckMessage proto.InternalMessageInfo

func (m *AckMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AckMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("main.Request_Type", Request_Type_name, Request_Type_value)
	proto.RegisterType((*Request)(nil), "main.Request")
	proto.RegisterType((*PingMessage)(nil), "main.PingMessage")
	proto.RegisterType((*AckMessage)(nil), "main.AckMessage")
}

func init() { proto.RegisterFile("vtn.proto", fileDescriptor_fdc682062a128624) }

var fileDescriptor_fdc682062a128624 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x2b, 0xc9, 0xd3,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x9a, 0xc8, 0xc8, 0xc5,
	0x1e, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0xa4, 0xc6, 0xc5, 0x52, 0x52, 0x59, 0x90, 0x2a,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x67, 0x24, 0xa4, 0x07, 0x52, 0xa0, 0x07, 0x95, 0xd4, 0x0b, 0xa9,
	0x2c, 0x48, 0x0d, 0x02, 0xcb, 0x0b, 0x19, 0x73, 0x71, 0x17, 0x64, 0xe6, 0xa5, 0xfb, 0xa6, 0x16,
	0x17, 0x27, 0xa6, 0xa7, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x1b, 0x09, 0x42, 0x94, 0x07, 0x20,
	0x24, 0x82, 0x90, 0x55, 0x29, 0x69, 0x72, 0xb1, 0x80, 0x8c, 0x10, 0x12, 0xe0, 0xe2, 0x09, 0xf0,
	0xf4, 0x73, 0x8f, 0xf7, 0x75, 0x0d, 0x0e, 0x76, 0x74, 0x77, 0x15, 0x60, 0x10, 0xe2, 0xe7, 0xe2,
	0x76, 0x74, 0xf6, 0x86, 0x0b, 0x30, 0x2a, 0x69, 0x73, 0x71, 0x23, 0x19, 0x23, 0x24, 0xc3, 0xc5,
	0x59, 0x92, 0x99, 0x9b, 0x5a, 0x5c, 0x92, 0x98, 0x5b, 0x00, 0x76, 0x1b, 0x73, 0x10, 0x42, 0x40,
	0xc9, 0x8e, 0x8b, 0xcb, 0x31, 0x39, 0x1b, 0xa6, 0x56, 0x88, 0x8b, 0x25, 0x39, 0x3f, 0x05, 0xe2,
	0x05, 0xd6, 0x20, 0x30, 0x1b, 0x55, 0x3f, 0x13, 0x9a, 0xfe, 0x24, 0x36, 0x70, 0x68, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x16, 0xeb, 0x3c, 0xb5, 0x1a, 0x01, 0x00, 0x00,
}
